name: deploy

on: 
  push:            
    branches:
      - main

jobs:
  build:
    name: server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run scripts in server react
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        script: |
          cd plantClubFrontend
          git add .
          git reset --hard
          git fetch
          git pull
          cd ~/plantserver
          docker-compose up --build -d
